apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ui
  namespace: test-ui
  annotations:
    kubernetes.io/ingress.class: nginx          # или свой класс, если другой
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - testui.mycum.ru
      secretName: testui-tls                     # сюда cert-manager положит сертификат
  rules:
    - host: testui.mycum.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-ui
                port:
                  number: 8000
