apiVersion: v1
kind: Service
metadata:
  name: test-ui
  namespace: test-ui
  labels:
    app: test-ui
spec:
  type: ClusterIP
  selector:
    app: test-ui
  ports:
    - name: http
      port: 8000
      targetPort: 8000
