apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-ui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bigcrazyfrog/argo_cd_test.git
    targetRevision: main
    path: k8s/test-ui
    helm:
      # valueFiles:
      #   - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: test-ui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
